fixed issue with logo sizing in open graph properties
OperationCodeKC/f5.vet-homepage pull request #5
Opened 2023-01-31 15:24 UTC by Christopher-Deo

Updated head section to include meta information and O.G. properties as well as added header with sample logo for site.

2023-02-02 01:50 UTC, JustinKSU requested changes
Good job.  Some small changes are required,

2023-02-02 01:50 UTC, JustinKSU commented on index.html
> +   <meta name="keywords" content="F5 Podcast">
I'll want to elaborate on these.  Minor: The spacing is not the same

2023-02-02 01:50 UTC, JustinKSU commented on index.html
> +    <meta property="og:image" content="img/f5-logo.png" height="150px" width="auto">
What our logo

2023-02-02 01:50 UTC, JustinKSU commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
I prefer any css/js is put with the project.  Please download and add the file.  Please keep the 6.3.0 in the folder so I know what version it is.

2023-02-02 01:50 UTC, JustinKSU commented on index.html
> +    <img id="logo" src="./images/f5-logo.png" alt="header logo for F5.vet site"/>
where the href?

2023-02-02 01:50 UTC, JustinKSU commented on index.html
> +<script type="text/javascript" src="js/script.js"></script>
Please remove until we need it

2023-02-04 00:12 UTC, Christopher-Deo commented on index.html
> +   <meta name="keywords" content="F5 Podcast">
spacing is fixed. I guess it didn't format on save as it should have.

2023-02-04 00:17 UTC, Christopher-Deo commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
I'm using the latest version of Bootstrap. It is in Alpha stage right now and the only way to connect to it is via CDN at this time.

2023-02-04 00:19 UTC, Christopher-Deo commented on index.html
> +    <img id="logo" src="./images/f5-logo.png" alt="header logo for F5.vet site"/>
No href at this time because there is no navigation component as of yet.  Didn't figure I needed a way to direct users back to this page right now as there is nowhere for them to go until we decide on a page structure. Once that is determined, I can plug in a navbar and place the appropriate link on the logo image.

2023-02-04 00:21 UTC, Christopher-Deo commented on index.html
> +<script type="text/javascript" src="js/script.js"></script>
These files are place here as I will be using them to develop the video player component and will need access to these CDN's as I do so. Working on that part as we speak.

2023-02-04 04:06 UTC, JustinKSU commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
Please download the css and put into our project.

2023-02-04 04:06 UTC, JustinKSU commented on index.html
> +    <img id="logo" src="./images/f5-logo.png" alt="header logo for F5.vet site"/>
You deleted <a href="https://operationcode.org">Operation Code</a> and I'm saying put it back.

2023-02-04 04:07 UTC, JustinKSU requested changes

2023-02-04 04:07 UTC, JustinKSU commented on index.html
> +<script type="text/javascript" src="js/script.js"></script>
? I guest it can stay.

2023-02-07 13:26 UTC, JustinKSU approved these changes

2023-02-07 13:27 UTC, merged